[pytest]
python_files=itest_*.py
python_classes=Itest
python_functions=itest
addopts = -rf --basetemp=_integration_tests_
# Max time in seconds for a single test (requires pytest-timeout).
# Use @pytest.mark.timeout(seconds) to change the value for a specific test.
timeout = 180
#-f loop on fail mode
#looponfailroots (pathlist) directories to check for changes
