"""This module contains a list of default tags for the AbinitInput object"""
from __future__ import print_function, division, unicode_literals, absolute_import

GROUND_STATE = "ground_state"
SCF = "scf"
RELAX = "relax"
ION_RELAX = "ion_relax"
IONCELL_RELAX = "ioncell_relax"
NSCF = "nscf"
BANDS = "bands"
DOS = "dos"
MOLECULAR_DYNACMICS="molecular_dynamics"
DFPT = "dfpt"
PHONON = "phonon"
DDK = "ddk"
DDE = "dde"
BEC = "bec"
PH_Q_PERT = "ph_q_pert"
STRAIN = "strain"
MANY_BODY = "many_body"
SIGMA = "sigma"
SCREENING = "screening"
BSE = "bse"
HYBRID = "hybrid"
DTE = "dte"
