.TH "Basis set convergence study and some more on flows, works, and tasks." "" "" "" ""
.SH Background
.PP
This lesson focuses on the convergence study of the completeness of the
basis set used.
In our case the basis set consists of plane waves.
Plane waves are inherently well suited to capture the periodic nature of
a crystalline solid.
In addition a plane wave basis set has the advantage that it introduces
only one convergence parameter, the kinetic energy cutoff.
.PP
The sharp features of the wavefunctions near the nucleus are however
problematic for plane waves.
Describing these features would require very high frequency plane waves.
In practice we will always use pseudo\-potentials in stead of the actual
nuclear potential to improve convergence.
Effectively a pseudopotential replaces the sharp coulomb potential of
the nucleus and the core electrons by something more smooth inside the
pseudization region that connects smoothly to the real potential outside
the pseudization region.
.PP
Needless to say a different pseudo potential will require a different
cutoff for the calculation to be converged.
In general norm\-conserving pseudos require a larger cut\-off that
ultra\-soft pseudos and Projector Augmented Wave \[aq]pseudos\[aq]
require even smaller cutoffs.
Moreover two pseudos of the same type for the same element may require
different cutoffs as well.
\[aq]Harder\[aq] (having a smaller pseudization radius) require larger
cutoffs than \[aq]softer\[aq] pseudos.
There are however many more properties of a pseudo that determine the
cutoff needed.
.SH The related abinit variables
.PP
As said the most important parameter in the energy cutoff, in abinit
ecut.
The most important input parameters concerning the basis set are:
.RS
.IP \[bu] 2
ecut
.IP \[bu] 2
dilatms
.IP \[bu] 2
ecutsm
.IP \[bu] 2
ecutdg
.RE
.PP
At this place they will not be discussed in detail.
In stead you are invited to read the abinit documentation on them.
The full description, directly from the abinit description is available
via the following function:
.RS
.RE
.PP
This will print the official abinit description of this inputvariable.
.PP
text for the commandline lesson
