.TH "K\-point convergence study for a semi\-conductor and an introduction
some of the basic concepts of the abipy library." "" "" "" ""
.SH Background
.PP
This lesson deals with the basic k\-point convergence study that is
needed in any DFT calculation of a solid.
In a DFT calculation of a solid the first Brillouin zone needs to be
discretized to enable the integration of various quantities.
Effectively the integrals are turned in to sums over k\-points.
For any result to be converged we need a k\-point mesh that is dense
enough, but at the same time as coarse as possible to make for an
efficient calculation.
Various types of materials require in general different densities of the
k\-point meshes.
In general metals need denser meshes than semiconductors.
Your first investigation into a new compound will quit often be a
k\-point convergence study.
.SH The related abinit variables
.PP
The abinit parameters concerned with the k\-point grid are:
.RS
.IP \[bu] 2
ngkpt
.IP \[bu] 2
shiftk
.IP \[bu] 2
occopt (see exercises)
.IP \[bu] 2
tsmear (see exercises)
.IP \[bu] 2
kptopt (see exercises)
.RE
.PP
At this place they will not be discussed in detail.
In stead you are invited to read the abinit documentation on them.
The full description, directly from the abinit description is available
via the following function:
.RS
.RE
.PP
This will print the official abinit description of this inputvariable.
.SH The course of this lesson
.PP
In the generation of this lesson by the python script all the input
files have been generated automatically.
You will.......
.PP
Executing the calculations using abirun
.PP
abirun.py
